### ISSUE TITLE
How to keep the cumulative data usage of a container across restarts

### ISSUE THREAD

**Issue by akshara-tg** [vergoh/vnstat-docker#15]
I have many docker containers and they have their respective bridge network. These appear as "br-xxxxxxx" in ifconfig o/p. 
The network ID get changed when a container is restarted. (i.e. "br-xxxxxxx" becomes "br-yyyyyyy").
Even if I set the same alias to "br-yyyyyyy" the usage associated with the "br-xxxxxxx" is no longer available in vnStat.

Any workaround to keep track of the usage of a container across restarts??

Thank you...

**Comment by vergoh** [comment]
vnStat can't see from inside its container which network is mapped to which container nor does vnStat support doing that from the host side either. It's a docker feature that the bridge network interface names are randomized by default.

The Docker documentation says that you can optionally define the name of the bridge network interface using the `com.docker.network.bridge.name` option: https://docs.docker.com/network/drivers/bridge/#options

If you define that for each container you are running then the bridge network interface name isn't going to change and vnStat will be able to track the traffic across restarts.

**Comment by akshara-tg** [comment]
@vergoh Thank you so much for the swift and detailed response. I was able to use `com.docker.network.bridge.name` and define a static name across container restarts.

You may close this item.

Thanks.
