### ISSUE TITLE
MiB, GiB → MB, GB  conversion

### ISSUE THREAD

**Issue by jaegwon** [vergoh/vnstat-docker#17]
I would like to change the unit from GiB to GB. Please tell me how.

https://vnstat.bonobono.com/

**Comment by vergoh** [comment]
That unit is configured using the `UnitMode` configuration file setting (see the man page https://humdi.net/vnstat/man/vnstat.conf.html) and it applies to both the command line and image outputs. However, it's not currently exposed as an environment variable so you'd need to map the `/etc/vnstat.conf` file to a volume or location you can modify or I'd need to do the necessary changes to expose it as an environment variable.

**Comment by jaegwon** [comment]
Solved. Thank you for answer.

**Comment by vergoh** [comment]
FYI, 4cbae9a adds support for using `VNSTAT_` prefixed environment variables for configuring any keyword in the configuration file. Adjusting `UnitMode` is as a result now possible using `VNSTAT_UnitMode` environment variable without having to map the configuration file outside the container.
