### ISSUE TITLE
Consider splitting vnstat and lighthttp in different containers

### ISSUE THREAD

**Issue by chrisliebaer** [vergoh/vnstat-docker#5]
I'm running a traefik reverse proxy for all my webservices. All my applications are properly dockered and do not have access to the hosts network stack (including traefik). Now obviously vnstat needs to to run on the host network to collect it's data, but the lighthttp doesn't. This makes it impossible for traefik to properly route incoming requests to lighthttp, since it can't access services bound to `127.0.0.1` on the **host network**. I could of course listen to multiple IP addresses but I don't have any that is only reachable by traefik, so I would have to bind lighthttp to a public interface or deploy firewall rules.

Since vnstati doesn't appear to need access to the vnstatd process, I would suggest moving lighthttp into it's own container and have them share the same volume. It would also allow to only run vnstatd or vnstati and not have to have have the database on the same host.

**Comment by vergoh** [comment]
Thanks for pointing out this kind of use case. I had previously tested the setup with traefik but looking at the docker-compose file now I didn't have lighttpd bound to `127.0.0.1` which most likely explains why it worked.

I think the easiest solution would be to introduce another environment variable for controlling if the vnstat daemon is started or not. With the default settings things would behave as they do currently but with the environment variables set differently it would be possibly to start one container with only the vnstat daemon running and another with only lighttpd running while still using the same image. That way any existing setup wouldn't get affected by the change while it would still allow isolating lighttpd to another container.

**Comment by vergoh** [comment]
https://github.com/vergoh/vnstat-docker/blob/master/docker-compose_isolated_httpd.yml should provide the solution for your scenario.

**Comment by chrisliebaer** [comment]
Thank you, that'll work 👌
