### ISSUE TITLE
How to access vnstat.conf

### ISSUE THREAD

**Issue by spammads** [vergoh/vnstat-docker#7]
Thanks for the work on this repo.
How can I access the vnstat.conf file normally stored under /etc/vnstat.conf?
Thanks in advance.

**Comment by vergoh** [comment]
If you just want to see the currently active configuration content then you can either run `docker exec vnstat vnstat --showconfig` or `docker exec vnstat cat /etc/vnstat.conf`. If you'd however want to have the possibility of modifying the configuration yourself, for example when the provided environment variables don't provide the configurability you'd want, then you'll have to first extract the current configuration file with either of the commands shown above, then do the wanted changes to the now local file and start the vnStat container again but this time map the local file as a volume which replaces the container's internal `/etc/vnstat.conf`.

Let me know if you'd prefer to have more detailed examples. If such is needed then please indicate if you are using `docker run` directly or `docker-compose`. The later usually becomes more practical especially as soon as any configuration is needed.

**Comment by spammads** [comment]
Sorry for the late reply.
I used docker-compose and mapped /etc/vnstat.conf to a corresponding file on the host. This works.
Really appreciate your work with this tool.
Works like a charm.
