### ISSUE TITLE
Set time zone through environment variable

### ISSUE THREAD

**Issue by agneevX** [vergoh/vnstat-docker#8]
Currently, timezone and localtime files must be mounted to set the correct time zone.

Adding the `tzdata` package to the Alpine Linux base image will let the time zone be set through the env var `TZ`.

**Comment by vergoh** [comment]
Thanks, that's a good point. I'll have to check if there was some reason why the `tzdata` package isn't already included in the list of packages that get installed, did this possibly change in some Alpine version along the way or did I just somehow manage to miss the interaction between the `tzdata` package and the `TZ` env.

**Comment by agneevX** [comment]
Thanks @vergoh, much appreciated!
