### ISSUE TITLE
Add /metrics endpoint for Prometheus

### ISSUE THREAD

**Issue by spammads** [vergoh/vnstat-docker#9]
Sorry if this is not the correct place to post. 
And thanks for this great tool.
I wonder if it would be possible to have the http-server serve a `/metrics`-endpoint.
This way metrics could be scraped by prometheus.

**Comment by vergoh** [comment]
This is indeed the correct place for this sort of request. In addition, I find this request interesting, so there's a high likelyhood of this getting implemented in a reasonable amount of time once I get a better understanding on what makes a good Prometheus metrics endpoint and what's the data vnStat can generate that's most suitable to be be served via that endpoint.

Did you have any specific data in mind you'd definitely want to see made available and do you know in advance if there's some type of data that's not suitable for Prometheus?

**Comment by spammads** [comment]
Glad to hear that.
Basically my problem is that prometheus _only_* lets you query a time-window relative to the query-execution time. Therefore it's a bit hard to evaluate the bandwidth used for the current month. If I execute a query today, with a timespan of 30 days I get data from July.

In vnstat.conf I set `monthlymonths = 1`.
So your metric under the json-path `$.interfaces[0].traffic.month[0].rx` shows me the used bandwidth for the current month. To have this metric available in prometheus would help me a lot.

I guess - generally speaking - it would be best to have metrics exposed, which deal with the current day, month and year (tx & rx). No need to expose metrics of yesterday the past months or years. Just the current ones. As persistence & retention would be handled by prometheus.

Here is an example of the `/metrics` endpoint the official Nginx-Exporter exposes. I think this is a good starting point as it just gives people a good set of basic metrics for handling basic Nginx-monitoring.

<img width="976" alt="Screenshot 2022-08-28 at 07 18 47" src="https://user-images.githubusercontent.com/63287042/187058820-0fa34ade-04d6-4ae3-941c-fd14d151cfa7.png">

*Not completely true. It is possible to use the `@` modifier to set an absolute timestamp. But in my situation this is not feasable.

Edit: `#` in Codeblocks do not work because of markdown. Replaced code-block with picture of Nginx-Exporter.

**Comment by vergoh** [comment]
I spent some time reading the following Prometheus documentation:

- https://prometheus.io/docs/instrumenting/writing_exporters/
- https://prometheus.io/docs/practices/naming/
- https://prometheus.io/docs/practices/instrumentation/#things-to-watch-out-for

and these gave a rather good idea of what should be there and what shouldn't.

vnStat didn't exactly have the sort of limited `--json` output for this purpose (although `--json a 1` is rather close) so I added a json summary output mode and made also timestamps directly available in https://github.com/vergoh/vnstat/commit/0885c9aac3f19328c904d95dec685b2f9d86c70a which will then allow `--json s 1` to contain all the necessary data without much extra.

With those changes done, it should now be mainly a matter of writing a cgi to convert that json to the wanted plain text content and configure lighttpd in the container to serve that cgi from `/metrics` + I'll have to configure some Prometheus container for validating that the data is indeed usable.

**Comment by vergoh** [comment]
The following metrics are now available from the `/metrics` endpoint of the latest `vergoh/vnstat:dev` image:

- vnstat_interface_total_received_bytes
- vnstat_interface_total_transmitted_bytes
- vnstat_interface_fiveminute_received_bytes
- vnstat_interface_fiveminute_transmitted_bytes
- vnstat_interface_hour_received_bytes
- vnstat_interface_hour_transmitted_bytes
- vnstat_interface_day_received_bytes
- vnstat_interface_day_transmitted_bytes
- vnstat_interface_month_received_bytes
- vnstat_interface_month_transmitted_bytes
- vnstat_interface_year_received_bytes
- vnstat_interface_year_transmitted_bytes

Interfaces are defined as labels with both the interface name and the alias being available. I'd suggest using `scrape_interval: 1m` for this endpoint as the data updates only every 5 minutes (at least with the default vnStat configuration).

**Comment by spammads** [comment]
Sorry for the late reply.
Works exactly as expected. Ticket can be closed.
Thank you very much for your effort.
Awesome.
